### ISSUE TITLE
建議不要用 barrel files

### ISSUE THREAD

**Issue by QzCurious** [DoubleTian-tw/pokemon-Gym#9]
### 建議不要用 barrel files

- 很容易載入過多不必要的 code
- 也讓回追程式的時候要多一步

### 過去為什麼廣為流傳

- 可以減少 `import` 時要打好多字
- 有被整理、群組化的感覺真好

### 我有看到 barrel file 的地方

https://github.com/DoubleTian-tw/pokemon-Gym/blob/e56d5b07522d702c5590fdd5f22f842998078b9c/src/components/Footer/index.js#L1-L3

https://github.com/DoubleTian-tw/pokemon-Gym/blob/e56d5b07522d702c5590fdd5f22f842998078b9c/src/components/Hero/index.js#L1-L2

https://github.com/DoubleTian-tw/pokemon-Gym/blob/e56d5b07522d702c5590fdd5f22f842998078b9c/src/components/Navbar/index.js#L1-L3

### 參考資料

這有個比較詳細介紹為什麼不要用 barrel files 的原因

[Barrel files and why you should STOP using them now](https://dev.to/tassiofront/barrel-files-and-why-you-should-stop-using-them-now-bc4)

**Comment by QzCurious** [comment]
這 issue 目前是小事，可改可不改，不改可以複習後就 close 掉

**Comment by DoubleTian-tw** [comment]
之前有聽說過在import套件時，也有提到引入整個套件使用或套件中單一檔案的區別，看起來這個與barrel files也有關係?
因為都是可能引入不需要用到的檔案，導致在bundle時過大以及unit test時引入不必要的內容

**Comment by QzCurious** [comment]
沒錯唷，現仍有許多用 barrel files 的套件，像 [@material-ui/icons](https://mui.com/material-ui/material-icons/) 就是一個大家常用的套件，他也是有 barrel files。

我原本是想先讓你簡單了解優缺，然後養成習慣就順其自然能做得比較好，你有去深入瞭解那就更好了。
